/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VeriTabani;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author GORKEM
 */
public class Personel extends javax.swing.JFrame {
    
    String kullad="root";
    String parola="";
    String db_name="vtio";
    String host="localhost";
    int port=3306;
    Connection con=null;
    String url="";
    DefaultTableModel model;
    DefaultComboBoxModel md = new DefaultComboBoxModel();
    Statement statement=null;
    ResultSet rs=null;
    
    /**
     * Creates new form Personel
     */
    public Personel() {
        initComponents();
        Baglan();
        ComboGetir();
    }
    public void Baglan(){
        String url="jdbc:mysql://"+host+":"+port+"/"+db_name+"?characterEncoding=utf8";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");            
            con=DriverManager.getConnection(url,kullad,parola);
            statement=con.createStatement();
            rs=statement.executeQuery("Select * from personel");        
            System.out.println("Bağlantı Başarılı");
        } catch (ClassNotFoundException ex) {
            System.out.println("Driver Bulunamadı");
        
        }catch(SQLException ex){
            System.out.println("Bağlantı Hatası");
        }

    }
    public void ComboGetir(){
        String sorgu="Select * from bolumler";
        DefaultComboBoxModel md1= new DefaultComboBoxModel();
        try {
            statement=con.createStatement();
            rs=statement.executeQuery(sorgu);
            while(rs.next()){
                md1.addElement(rs.getString("bolumad"));
            }
            cmb_bolum.setModel(md1);
        } catch (SQLException ex) {
            Logger.getLogger(Personel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void BaglantiKapat(){
        try {
            con.close();
        } catch (Exception e) {
            System.out.println("BAĞLANTI KAPANMADI!");
        }
     
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_tcno = new javax.swing.JTextField();
        txt_ad = new javax.swing.JTextField();
        txt_soyad = new javax.swing.JTextField();
        txt_bolum = new javax.swing.JTextField();
        btn_Getir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        btn_sonraki = new javax.swing.JButton();
        btn_Guncelle = new javax.swing.JButton();
        btn_Ekle = new javax.swing.JButton();
        btn_Sil = new javax.swing.JButton();
        btn_ara = new javax.swing.JButton();
        cmb_Ara = new javax.swing.JComboBox<>();
        cmb_bolum = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TC Kimlik No :");

        jLabel2.setText("Ad :");

        jLabel3.setText("Soyad :");

        jLabel4.setText("Bölüm :");

        btn_Getir.setText("Kayıt Getir");
        btn_Getir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GetirActionPerformed(evt);
            }
        });

        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC", "Ad", "Soyad", "Bölüm"
            }
        ));
        tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo);

        btn_sonraki.setText("Sonraki");
        btn_sonraki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sonrakiActionPerformed(evt);
            }
        });

        btn_Guncelle.setText("Güncelle");
        btn_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuncelleActionPerformed(evt);
            }
        });

        btn_Ekle.setText("Ekle");
        btn_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EkleActionPerformed(evt);
            }
        });

        btn_Sil.setText("Sil");
        btn_Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SilActionPerformed(evt);
            }
        });

        btn_ara.setText("Ara");
        btn_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_araActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_soyad, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txt_ad)
                            .addComponent(txt_bolum, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_tcno, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_bolum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmb_Ara, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_sonraki)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Getir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ara, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_Getir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Guncelle)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btn_Ekle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Sil))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_ara)
                                    .addComponent(cmb_Ara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(8, 8, 8)
                        .addComponent(btn_sonraki))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_tcno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_bolum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_bolum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GetirActionPerformed
        try {            
            statement=con.createStatement();
            rs=statement.executeQuery("Select * from personel");
            model=(DefaultTableModel)tablo.getModel();
            rs.next();
            txt_tcno.setText(rs.getString("tcno"));
            txt_ad.setText(rs.getString("ad"));
            txt_soyad.setText(rs.getString("s"));
            txt_bolum.setText(rs.getString("bolum"));
 //-----------------------------------------------------------------------------------------                     
            statement=con.createStatement();
            rs=statement.executeQuery("Select * from personel");
           // String sorgu="Select tcno,ad,soyad,bolumad from ogr INNER JOIN bolumler ON ogr.bolumid=bolumler.bolumid";
            model=(DefaultTableModel)tablo.getModel();
            while(rs.next()){
            model.addRow(new Object[]{rs.getString("tcno"),rs.getString("ad"),rs.getString("s"),rs.getString("bolum")});            
            //md.addElement(rs.getString("bolum"));
            }
            tablo.setModel(model);  
            //cmb_Ara.setModel(md);
            TabloYenile();
        } catch (SQLException ex) {
            Logger.getLogger(Personel.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_btn_GetirActionPerformed

    private void btn_sonrakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sonrakiActionPerformed
        try {
            if(rs.last()){rs.first();}
            else if(rs.first()){
            rs.next();
            }
            txt_tcno.setText(rs.getString("tcno"));
            txt_ad.setText(rs.getString("ad"));
            txt_soyad.setText(rs.getString("s"));
            txt_bolum.setText(rs.getString("bolumad"));
        } catch (SQLException ex) {
            Logger.getLogger(Personel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_sonrakiActionPerformed
public void TabloYenile(){
    try {
        statement=con.createStatement();
        rs=statement.executeQuery("Select * from personel");
        TabloTemizle();
        model=(DefaultTableModel)tablo.getModel();
        while(rs.next()){
            model.addRow(new Object[]{rs.getString("tcno"),rs.getString("ad"),rs.getString("s"),rs.getString("bolum")});
        }
    } catch (Exception e) {
    }    
}
public void TabloTemizle(){
    model=(DefaultTableModel)tablo.getModel();
    model.getDataVector().removeAllElements();
}
    private void btn_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuncelleActionPerformed
        String sorgu="UPDATE personel set ad=?, s=?, bolum=? where tcno=?";
        try {
    
            PreparedStatement pst=con.prepareStatement(sorgu);
            pst.setString(1,txt_ad.getText());
            pst.setString(2,txt_soyad.getText());
            pst.setString(3,txt_bolum.getText());
            pst.setString(4,txt_tcno.getText());
            int s=pst.executeUpdate();
            if(s>0){
                JOptionPane.showMessageDialog(this,"Güncelleme Başarılı");
                TabloYenile();
            }
        } catch (SQLException e) {
        }  
    }//GEN-LAST:event_btn_GuncelleActionPerformed

    private void btn_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EkleActionPerformed
        String sorgu="Insert into personel (tcno,ad,s,bolum) value(?,?,?,?)";
        try {
            PreparedStatement pst=con.prepareStatement(sorgu);
            pst.setString(2,txt_ad.getText());
            pst.setString(3,txt_soyad.getText());
            pst.setString(4,txt_bolum.getText());
            pst.setString(1,txt_tcno.getText());
            int s=pst.executeUpdate();
            if(s>0){
                JOptionPane.showMessageDialog(this,"Güncelleme Başarılı");
                TabloYenile();
            }
        } catch (SQLException e) {
        }  
    }//GEN-LAST:event_btn_EkleActionPerformed

    private void tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloMouseClicked
        model=(DefaultTableModel)tablo.getModel();
        int secilen=tablo.getSelectedRow();
        txt_tcno.setText(model.getValueAt(secilen,0).toString());
        txt_ad.setText(model.getValueAt(secilen,1).toString());
        txt_soyad.setText(model.getValueAt(secilen,2).toString());
        txt_bolum.setText(model.getValueAt(secilen,3).toString());
    }//GEN-LAST:event_tabloMouseClicked

    private void btn_SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SilActionPerformed
               String sorgu="Delete from personel where tcno=?";
        try {
            PreparedStatement pst=con.prepareStatement(sorgu);
            pst.setString(1,txt_tcno.getText());
            
            int s=pst.executeUpdate();
            if(s>0){
                JOptionPane.showMessageDialog(this,"Güncelleme Başarılı");
                TabloYenile();
            }
        } catch (SQLException e) {
        } 
    }//GEN-LAST:event_btn_SilActionPerformed

    private void btn_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_araActionPerformed
        String b=cmb_Ara.getSelectedItem().toString();
        String sorgu="SELECT * FROM PERSONEL WHERE bolum='"+b+"'";
        TabloTemizle();
        try {
            rs=statement.executeQuery(sorgu);
        } catch (SQLException ex) {
            Logger.getLogger(Personel.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("tcno"),rs.getString("ad"),rs.getString("s"),rs.getString("bolum")});
            }
            tablo.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Personel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_araActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ekle;
    private javax.swing.JButton btn_Getir;
    private javax.swing.JButton btn_Guncelle;
    private javax.swing.JButton btn_Sil;
    private javax.swing.JButton btn_ara;
    private javax.swing.JButton btn_sonraki;
    private javax.swing.JComboBox<String> cmb_Ara;
    private javax.swing.JComboBox<String> cmb_bolum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablo;
    private javax.swing.JTextField txt_ad;
    private javax.swing.JTextField txt_bolum;
    private javax.swing.JTextField txt_soyad;
    private javax.swing.JTextField txt_tcno;
    // End of variables declaration//GEN-END:variables
}
