/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java2;

import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author GORKEM
 */
public class Hafta_11_Map extends javax.swing.JFrame {
Map<String,Integer>siparis=new LinkedHashMap<String,Integer>();
    /**
     * Creates new form Hafta_11_Map
     */
    public Hafta_11_Map() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_kahvalti = new javax.swing.JCheckBox();
        cb_corba = new javax.swing.JCheckBox();
        cb_tost = new javax.swing.JCheckBox();
        btn_siparis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb_kahvalti.setText("Kahvaltı- 100₺");

        cb_corba.setText("Çorba- 80₺");

        cb_tost.setText("Tost- 50₺");

        btn_siparis.setText("Sipariş");
        btn_siparis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siparisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_tost)
                    .addComponent(cb_corba)
                    .addComponent(cb_kahvalti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_siparis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(cb_kahvalti)
                .addGap(18, 18, 18)
                .addComponent(cb_corba)
                .addGap(18, 18, 18)
                .addComponent(cb_tost)
                .addGap(26, 26, 26)
                .addComponent(btn_siparis)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_siparisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siparisActionPerformed
        
        if(cb_kahvalti.isSelected()){
            siparis.put("Kahvaltı",100);
        }else{
            siparis.remove("Kahvaltı");
        }
        if(cb_corba.isSelected()){
            siparis.put("Çorba", 80);
        }else{
            siparis.remove("Çorba");
        }
        if(cb_tost.isSelected()){
            siparis.put("Tost",50);
        }else{
            siparis.remove("Tost");
        }
        String sp;int tutar=0;
        for(Map.Entry<String,Integer>al:siparis.entrySet()){
            sp=al.getKey();
            tutar=al.getValue();
            JOptionPane.showMessageDialog(this,"Siparişlerim\n"+sp+"\nTutar: "+tutar);
        }
        
    }//GEN-LAST:event_btn_siparisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hafta_11_Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hafta_11_Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hafta_11_Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hafta_11_Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hafta_11_Map().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_siparis;
    private javax.swing.JCheckBox cb_corba;
    private javax.swing.JCheckBox cb_kahvalti;
    private javax.swing.JCheckBox cb_tost;
    // End of variables declaration//GEN-END:variables
}
