/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java2;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GORKEM
 */
public class Hafta_08_Tablo2 extends javax.swing.JFrame {
    int bakiyem=0;
    int yuklenen=0;
    /**
     * Creates new form Hafta_08_Tablo2
     */
    public Hafta_08_Tablo2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_izle = new javax.swing.JTable();
        btn_cek = new javax.swing.JButton();
        cb_drum = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btn_yukle = new javax.swing.JButton();
        cb_tutar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_izle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Yüklenen", "Çekim", "Drum", "Bakiyem"
            }
        ));
        jScrollPane1.setViewportView(tbl_izle);

        btn_cek.setText("Bakiye Çek");
        btn_cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekActionPerformed(evt);
            }
        });

        cb_drum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tam", "Öğrenci" }));

        jLabel1.setText("Yüklenecek Tutar: ");

        btn_yukle.setText("Bakiye Yükle");
        btn_yukle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yukleActionPerformed(evt);
            }
        });

        cb_tutar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "50", "100", "200" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cb_drum, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_yukle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_tutar, 0, 126, Short.MAX_VALUE))
                    .addComponent(btn_cek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cb_tutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_yukle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_drum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_cek, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_yukleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yukleActionPerformed
        DefaultTableModel modelim=(DefaultTableModel)tbl_izle.getModel();  
        int index=cb_tutar.getSelectedIndex();
        if(index==0){
            yuklenen=10;
            bakiyem=bakiyem+yuklenen;
        }else if(index==1){
            yuklenen=20;
            bakiyem=bakiyem+yuklenen;
        }else if(index==2){
            yuklenen=50;
            bakiyem=bakiyem+yuklenen;
        }else if(index==3){
            yuklenen=100;
            bakiyem=bakiyem+yuklenen;
        }else if(index==4){
            yuklenen=200;
            bakiyem=bakiyem+yuklenen;
        }                       
        modelim.addRow(new Object[]{yuklenen,"-","-",bakiyem});       
    }//GEN-LAST:event_btn_yukleActionPerformed

    private void btn_cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekActionPerformed
        DefaultTableModel modelim=(DefaultTableModel)tbl_izle.getModel();
        int index2=cb_drum.getSelectedIndex();
        int cekim=0;
        String drum="";
        if(index2==1){
            cekim=7;
            drum="Ogrenci";
            bakiyem=bakiyem-cekim;
        }else if(index2==0){
            cekim=12;
            drum="Tam";
            bakiyem=bakiyem-cekim;
                    
        }
        modelim.addRow(new Object[]{"-",drum,cekim,bakiyem});
    }//GEN-LAST:event_btn_cekActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hafta_08_Tablo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cek;
    private javax.swing.JButton btn_yukle;
    private javax.swing.JComboBox<String> cb_drum;
    private javax.swing.JComboBox<String> cb_tutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_izle;
    // End of variables declaration//GEN-END:variables
}
