/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java2;

import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author GORKEM
 */
public class Hafta_12_Set extends javax.swing.JFrame {

    /**
     * Creates new form Hafta_12_Set
     */
    public Hafta_12_Set() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_Java = new javax.swing.JCheckBox();
        cb_C = new javax.swing.JCheckBox();
        cb_Python = new javax.swing.JCheckBox();
        btn_Sec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb_Java.setText("Java");
        cb_Java.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_JavaActionPerformed(evt);
            }
        });

        cb_C.setText("C#");
        cb_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CActionPerformed(evt);
            }
        });

        cb_Python.setText("Python");
        cb_Python.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_PythonActionPerformed(evt);
            }
        });

        btn_Sec.setText("Seç");
        btn_Sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_C)
                            .addComponent(cb_Python)
                            .addComponent(cb_Java)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btn_Sec, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(cb_Java)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_Python)
                .addGap(24, 24, 24)
                .addComponent(btn_Sec)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_JavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_JavaActionPerformed
     
    }//GEN-LAST:event_cb_JavaActionPerformed

    private void cb_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CActionPerformed

    private void cb_PythonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_PythonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_PythonActionPerformed

    private void btn_SecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SecActionPerformed
        Set<String> secilen=new LinkedHashSet<String>();
        if(cb_Java.isSelected()){
            secilen.add("Java");
        }else{
            secilen.remove("Java");
        }
        if(cb_C.isSelected()){
            secilen.add("C#");
        }else{
            secilen.remove("C#");
        }
        if(cb_Python.isSelected()){
            secilen.add("Python");
        }else{
            secilen.remove("Python");
        }
        String derslerim="";
        for(String d:secilen){
            derslerim=d+"\n";
            JOptionPane.showMessageDialog(this,"Seçtiğim derslerim "+derslerim);
        }
    }//GEN-LAST:event_btn_SecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hafta_12_Set.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hafta_12_Set.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hafta_12_Set.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hafta_12_Set.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hafta_12_Set().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sec;
    private javax.swing.JCheckBox cb_C;
    private javax.swing.JCheckBox cb_Java;
    private javax.swing.JCheckBox cb_Python;
    // End of variables declaration//GEN-END:variables
}
